//! The Minecraft map: a world generated by MinecraftOSS, played on top of a
//! small IW4 map loaded only for the shared weapon, body and menu content.
//! None of that map's world is shown or collided with.
use asset_transport::{GamesRoot, ZoneFile};

pub const ZONE: &str = "minecraft:overworld";
/// The map whose level script the generated Minecraft world runs.
pub const PROXY_MAP: &str = "mp_rust";

/// The Minecraft maps: the generated world, and replicas of MW2 maps built
/// from the map each stands on (its zone, and whether it's a replica).
const WORLDS: [(&str, &str, bool); 3] = [
    (ZONE, "mp_rust", false),
    ("minecraft:rust", "mp_rust", true),
    ("minecraft:terminal", "mp_terminal", true),
];

fn world(zone: &str) -> Option<(&'static str, &'static str, bool)> {
    let zone = zone.trim();
    WORLDS.into_iter().find(|(name, ..)| name.eq_ignore_ascii_case(zone))
}

pub fn is_minecraft(zone: &str) -> bool {
    world(zone).is_some()
}

/// Whether the Minecraft map is a replica of the MW2 map it stands on.
pub fn is_replica(zone: &str) -> bool {
    world(zone).or_else(|| zone.split_once(':').and_then(|(_, rest)| world(rest))).is_some_and(|(.., replica)| replica)
}

/// The MW2 map a Minecraft map stands on (its weapons, bodies and level
/// script; a replica's geometry too).
pub fn proxy_map(zone: &str) -> &'static str {
    world(zone).or_else(|| zone.split_once(':').and_then(|(_, rest)| world(rest))).map_or(PROXY_MAP, |(_, map, _)| map)
}

fn proxy_zone(zone: &str) -> String {
    format!("iw4:{}", proxy_map(zone))
}

/// Whether a load's zone, with or without its content namespace, is the
/// Minecraft map.
pub fn is_minecraft_load(zone: &str) -> bool {
    is_minecraft(zone) || zone.split_once(':').is_some_and(|(_, rest)| is_minecraft(rest))
}

/// Where the world's Minecraft files are: a MinecraftOSS checkout named by
/// `MINECRAFTOSS_ROOT`, else the files fetched from Mojang once they are in.
pub fn root() -> Option<std::path::PathBuf> {
    if let Some(root) = std::env::var_os("MINECRAFTOSS_ROOT").map(std::path::PathBuf::from)
        && root.join("datapacks").is_dir()
    {
        return Some(root);
    }
    crate::minecraft_setup::ready()
}

/// Starts fetching Minecraft's files from Mojang when nothing supplies them.
pub fn prepare() {
    if root().is_none() {
        crate::minecraft_setup::begin();
    }
}

pub fn find_zone_file(root_dir: &GamesRoot, zone: &str) -> Result<ZoneFile, String> {
    if !is_minecraft_load(zone) {
        return asset_transport::find_zone_file(root_dir, zone);
    }
    let checkout = match root() {
        Some(root) => root,
        None => {
            // A first run straight into this map waits for Mojang's files.
            crate::minecraft_setup::begin();
            diag::info!(World, "Minecraft map: waiting for Minecraft's files from Mojang");
            // Briefly: a load held much longer does not come back cleanly,
            // and the fetch carries on for the next try.
            crate::minecraft_setup::wait(std::time::Duration::from_secs(90))
                .ok_or_else(crate::minecraft_setup::status)?
        }
    };
    let mut proxy = asset_transport::find_zone_file(root_dir, &proxy_zone(zone))?;
    proxy.zone_name = world(zone)
        .or_else(|| zone.split_once(':').and_then(|(_, rest)| world(rest)))
        .map_or(ZONE, |(name, ..)| name)
        .to_owned();
    proxy.alias_note = Some(format!("Minecraft world from {}", checkout.display()));
    Ok(proxy)
}

/// The installed map packs, with the Minecraft world as a pack of its own
/// when the map it stands in for is installed.
pub fn list_mp_map_packs(root_dir: &GamesRoot) -> Vec<asset_transport::MapPack> {
    prepare();
    let mut packs = asset_transport::list_mp_map_packs(root_dir);
    let maps = installed_worlds(root_dir);
    if !maps.is_empty() {
        packs.push(asset_transport::MapPack { label: "Minecraft".to_owned(), maps });
    }
    packs
}

pub fn list_mp_maps(root_dir: &GamesRoot) -> Vec<String> {
    let mut maps = asset_transport::list_mp_maps(root_dir);
    // Listed before Mojang's files are in: loading it waits for them.
    prepare();
    maps.extend(installed_worlds(root_dir));
    maps.sort();
    maps.dedup();
    maps
}

/// The Minecraft maps whose MW2 map is installed.
fn installed_worlds(root_dir: &GamesRoot) -> Vec<String> {
    WORLDS
        .iter()
        .filter(|(_, map, _)| asset_transport::find_zone_file(root_dir, &format!("iw4:{map}")).is_ok())
        .map(|(name, ..)| (*name).to_owned())
        .collect()
}
